const en = {
  draftConflict: "Another draft is already open. Your startup draft has been kept.",
  copyDraft: "Copy saved draft",
  heading: "What should we work on?",
  placeholder: "Ask anything, or describe a task…",
  home: "New task",
  work: "Work",
  projects: "Projects",
  workspaces: "Workspaces",
  recent: "Recent tasks",
  send: "Send",
  cancel: "Cancel send",
  retry: "Retry",
  loading: "Starting DJL. You can write while it loads.",
  sending: "Send queued. Waiting for DJL to be ready…",
  recovered: "Your previous send could not be confirmed. Review your draft before sending again.",
  sendFailed: "DJL could not start. Your draft is still here.",
  modelRequired: "Choose a model when DJL is ready to send.",
  storageError: "Draft is only in memory. Local storage is unavailable.",
  minimize: "Minimize",
  maximize: "Maximize",
  restore: "Restore",
  close: "Close",
};
type StartupCopy = typeof en;
const copies: Record<string, StartupCopy> = {
  en,
  "zh-Hans": {
    draftConflict: "已有另一份草稿。启动时的草稿已保留。",
    copyDraft: "复制已保存的草稿",
    heading: "我们开始做什么？",
    placeholder: "提出问题，或描述任务…",
    home: "新任务",
    work: "工作",
    projects: "项目",
    workspaces: "工作区",
    recent: "最近任务",
    send: "发送",
    cancel: "取消发送",
    retry: "重试",
    loading: "DJL 正在启动，你可以先输入。",
    sending: "已排队，等待 DJL 就绪…",
    recovered: "无法确认上次发送。请检查草稿后重新发送。",
    sendFailed: "DJL 未能启动，草稿仍在。",
    modelRequired: "DJL 就绪后请选择模型以发送。",
    storageError: "草稿仅保存在内存中，本地存储不可用。",
    minimize: "最小化",
    maximize: "最大化",
    restore: "还原",
    close: "关闭",
  },
  "zh-Hant": {
    draftConflict: "已有另一份草稿。啟動時的草稿已保留。",
    copyDraft: "複製已儲存的草稿",
    heading: "我們開始做什麼？",
    placeholder: "提出問題，或描述任務…",
    home: "新任務",
    work: "工作",
    projects: "專案",
    workspaces: "工作區",
    recent: "最近任務",
    send: "傳送",
    cancel: "取消傳送",
    retry: "重試",
    loading: "DJL 正在啟動，你可以先輸入。",
    sending: "已排入佇列，等待 DJL 就緒…",
    recovered: "無法確認上次傳送。請檢查草稿後重新傳送。",
    sendFailed: "DJL 未能啟動，草稿仍在。",
    modelRequired: "DJL 就緒後請選擇模型以傳送。",
    storageError: "草稿僅儲存在記憶體中，本機儲存空間無法使用。",
    minimize: "最小化",
    maximize: "最大化",
    restore: "還原",
    close: "關閉",
  },
  ja: {
    draftConflict: "別の下書きが開いています。起動時の下書きは保存されています。",
    copyDraft: "保存した下書きをコピー",
    heading: "何に取り組みましょうか？",
    placeholder: "質問やタスクを入力…",
    home: "新しいタスク",
    work: "作業",
    projects: "プロジェクト",
    workspaces: "ワークスペース",
    recent: "最近のタスク",
    send: "送信",
    cancel: "送信をキャンセル",
    retry: "再試行",
    loading: "DJL を起動中です。入力を始められます。",
    sending: "送信を予約しました。DJL の準備を待っています…",
    recovered: "前回の送信を確認できませんでした。下書きを確認してから再送信してください。",
    sendFailed: "DJL を起動できませんでした。下書きは保持されています。",
    modelRequired: "DJL の準備ができたらモデルを選択してください。",
    storageError: "下書きはメモリ内にのみ保持されています。ローカル保存は利用できません。",
    minimize: "最小化",
    maximize: "最大化",
    restore: "元に戻す",
    close: "閉じる",
  },
  ko: {
    draftConflict: "다른 초안이 열려 있습니다. 시작 시 작성한 초안은 보관됩니다.",
    copyDraft: "저장된 초안 복사",
    heading: "무엇을 해볼까요?",
    placeholder: "질문하거나 작업을 설명하세요…",
    home: "새 작업",
    work: "작업",
    projects: "프로젝트",
    workspaces: "워크스페이스",
    recent: "최근 작업",
    send: "보내기",
    cancel: "보내기 취소",
    retry: "다시 시도",
    loading: "DJL을 시작하는 중입니다. 먼저 입력할 수 있습니다.",
    sending: "전송 대기 중입니다. DJL 준비를 기다리고 있습니다…",
    recovered: "이전 전송을 확인할 수 없습니다. 초안을 검토한 후 다시 보내세요.",
    sendFailed: "DJL을 시작하지 못했습니다. 초안은 유지됩니다.",
    modelRequired: "DJL이 준비되면 모델을 선택하세요.",
    storageError: "초안이 메모리에만 있습니다. 로컬 저장소를 사용할 수 없습니다.",
    minimize: "최소화",
    maximize: "최대화",
    restore: "복원",
    close: "닫기",
  },
  "es-419": {
    draftConflict: "Ya hay otro borrador abierto. Conservamos el borrador del inicio.",
    copyDraft: "Copiar borrador guardado",
    heading: "¿En qué trabajamos?",
    placeholder: "Pregunta algo o describe una tarea…",
    home: "Nueva tarea",
    work: "Trabajo",
    projects: "Proyectos",
    workspaces: "Espacios de trabajo",
    recent: "Tareas recientes",
    send: "Enviar",
    cancel: "Cancelar envío",
    retry: "Reintentar",
    loading: "DJL se está iniciando. Puedes empezar a escribir.",
    sending: "Envío en espera. Esperando a que DJL esté listo…",
    recovered:
      "No se pudo confirmar el envío anterior. Revisa el borrador antes de enviarlo de nuevo.",
    sendFailed: "DJL no pudo iniciarse. Tu borrador sigue aquí.",
    modelRequired: "Selecciona un modelo cuando DJL esté listo para enviar.",
    storageError: "El borrador solo está en memoria. El almacenamiento local no está disponible.",
    minimize: "Minimizar",
    maximize: "Maximizar",
    restore: "Restaurar",
    close: "Cerrar",
  },
  fr: {
    draftConflict: "Un autre brouillon est ouvert. Le brouillon de démarrage a été conservé.",
    copyDraft: "Copier le brouillon enregistré",
    heading: "Sur quoi allons-nous travailler ?",
    placeholder: "Posez une question ou décrivez une tâche…",
    home: "Nouvelle tâche",
    work: "Travail",
    projects: "Projets",
    workspaces: "Espaces de travail",
    recent: "Tâches récentes",
    send: "Envoyer",
    cancel: "Annuler l’envoi",
    retry: "Réessayer",
    loading: "DJL démarre. Vous pouvez commencer à écrire.",
    sending: "Envoi en attente. DJL se prépare…",
    recovered:
      "L’envoi précédent n’a pas pu être confirmé. Vérifiez le brouillon avant de le renvoyer.",
    sendFailed: "DJL n’a pas pu démarrer. Votre brouillon est toujours là.",
    modelRequired: "Choisissez un modèle lorsque DJL sera prêt à envoyer.",
    storageError: "Le brouillon est uniquement en mémoire. Le stockage local est indisponible.",
    minimize: "Réduire",
    maximize: "Agrandir",
    restore: "Restaurer",
    close: "Fermer",
  },
};
export function getStartupCopy(locale: string): StartupCopy {
  return copies[locale] ?? en;
}
