export type Locale = "en" | "zh";
export type ConsoleTab = "plan" | "tools" | "review";

type BootLine = { text: string; ok?: boolean };

export const codeLines = [
  "import { Router } from 'express'",
  "import { z } from 'zod'",
  "import { createUser } from '../lib/user'",
  "",
  "const router = Router()",
  "const Body = z.object({",
  "  name: z.string().min(1),",
  "  email: z.string().email(),",
  "})",
  "",
  "router.post('/users', async (req, res) => {",
  "  const parsed = Body.safeParse(req.body)",
  "  if (!parsed.success) {",
  "    return res.status(400).json({ error: 'Invalid input' })",
  "  }",
  "  const user = await createUser(parsed.data)",
  "  res.status(201).json(user)",
  "})",
];

// simple-icons slugs rendered white into the Icon Cloud: the runtimes,
// languages, editors and providers DJL drives.
export const iconSlugs = [
  "typescript",
  "javascript",
  "python",
  "rust",
  "go",
  "react",
  "nextdotjs",
  "nodedotjs",
  "docker",
  "git",
  "github",
  "githubcopilot",
  "ollama",
  "huggingface",
  "pytorch",
  "postgresql",
  "redis",
  "linux",
  "apple",
  "neovim",
];

export const iconImages = iconSlugs.map((s) => `https://cdn.simpleicons.org/${s}/0b1118`);

// The curated local models DJL offers, mirrored by hand from
// apps/server/src/localModels/catalog.ts. This app builds standalone and is mirrored to its own
// deployment repository, so it cannot import from the server workspace; update both together.
//
// `agent: false` is `supportsToolCalls: false` there. Such a model chats but cannot drive tools,
// and handing it tool definitions stalls silently rather than erroring — which is the one thing a
// visitor must not have to discover by watching the agent hang.
export const localModelCatalog = [
  { id: "qwen3-1.7b", name: "Qwen3 1.7B", minMemoryGb: 4, downloadGb: 1.4, agent: false },
  { id: "qwen3.5-2b", name: "Qwen3.5 2B", minMemoryGb: 8, downloadGb: 1.9, agent: false },
  { id: "granite-4.1-3b", name: "Granite 4.1 3B", minMemoryGb: 8, downloadGb: 2.1, agent: true },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen2.5 Coder 7B",
    minMemoryGb: 16,
    downloadGb: 4.36,
    agent: true,
  },
  { id: "gpt-oss-20b", name: "GPT-OSS 20B", minMemoryGb: 16, downloadGb: 13, agent: true },
  { id: "qwen3-coder-30b", name: "Qwen3 Coder 30B", minMemoryGb: 32, downloadGb: 19, agent: true },
] as const;

export type LocalModelRow = (typeof localModelCatalog)[number];

// Weights are fractional gibibytes; a fixed decimal count would print "13.00 GB", which reads as
// precision the catalog does not claim.
export function formatGb(value: number): string {
  return `${Number(value.toFixed(2))} GB`;
}

export const content = {
  en: {
    htmlLang: "en",
    dir: "Bilingual agent command center",
    nav: [
      { id: "routing", label: "Routing" },
      { id: "workflow", label: "Workflow" },
      { id: "bilingual", label: "Bilingual" },
      { id: "stack", label: "Stack" },
      { id: "pipeline", label: "Pipeline" },
    ],
    getStarted: "Open workspace",
    enterHint: "press any key to enter",
    skip: "skip intro",
    boot: {
      brand: "DJL",
      label: "LOCAL RUNTIME",
      lines: [
        { text: "initializing DJL kernel" },
        { text: "mounting local runtime", ok: true },
        { text: "model: deepseek-v4-flash", ok: true },
        { text: "tools: 14 registered", ok: true },
        { text: "workspace: scoped and private", ok: true },
        { text: "online bridge: standby" },
        { text: "calibrating intent router" },
      ] as BootLine[],
      ready: "AGENT AWAKE",
    },
    hero: {
      status: "LOCAL / ONLINE READY",
      coord: "EN / 中文",
      kicker: "An intelligence that runs where you are",
      titleLines: ["Agent wakes", "on your machine."],
      body: "Run a bilingual coding agent locally, route tasks online when needed, and approve every file change before it lands.",
      primary: "Open workspace",
      secondary: "Read the docs",
      stats: [
        { k: "Local-first", v: "private by default" },
        { k: "14 tools", v: "registered & sandboxed" },
        { k: "EN / 中文", v: "one shared context" },
        { k: "Review-gated", v: "every change" },
      ],
      hud: {
        model: "MODEL",
        modelValue: "DJL-CORE",
        state: "STATE",
        stateValue: "AWAKE",
      },
    },
    field: {
      depthLabel: "DEPTH",
      descend: "descend the stack",
      strata: ["SURFACE", "ROUTER", "WORKFLOW", "BILINGUAL", "STACK", "PIPELINE", "KERNEL"],
      glyphs: [
        "› route → local",
        "tool · read_file ✓",
        "kernel · deepseek-v4-flash",
        "intent classified",
        "diff · awaiting review",
        "sandbox · scoped",
        "中文 ↔ EN",
        "运行测试 ✓",
      ],
    },
    console: {
      tag: "LIVE SESSION",
      task: "Build a user endpoint with validation and tests",
      state: "in progress",
      tabs: [
        { id: "plan" as ConsoleTab, label: "Plan" },
        { id: "tools" as ConsoleTab, label: "Tools" },
        { id: "review" as ConsoleTab, label: "Review" },
      ],
      timeline: [
        ["Plan", "create steps"],
        ["Tools", "run selected tools"],
        ["Read", "src/routes/users.ts"],
        ["Edit", "src/routes/users.ts"],
        ["Test", "npm test"],
        ["Review", "awaiting your approval"],
      ],
      file: "src/routes/users.ts",
      terminal: { cmd: "npm test", pass: "PASS", file: "tests/users.test.ts" },
      tests: ["creates a user (23 ms)", "validates email (18 ms)"],
      testSummary: "2 passed · 541 ms",
      review: {
        title: "Review change",
        action: "Edit file",
        summaryLabel: "Summary",
        summary: "Added POST /users with validation and tests.",
        impactLabel: "Impact",
        impact: ["adds new route", "adds input validation", "adds tests"],
        filesLabel: "Files",
        files: ["src/routes/users.ts", "tests/users.test.ts"],
        approve: "Approve & apply",
        request: "Request changes",
        cancel: "Cancel / rollback",
      },
    },
    routing: {
      index: "01",
      tag: "Routing",
      title: "Choose where every task runs",
      body: "Route work to local or online runtimes by sensitivity and speed. Your code and data stay scoped exactly where you put them.",
      workspace: "Your workspace",
      router: "DJL router",
      local: "Local",
      online: "Online",
      localBody: "Private by default. Nothing leaves the device.",
      onlineBody: "Best for reach. Secure connections only.",
      items: [
        { k: "Files", v: "scoped to project" },
        { k: "Environment", v: "isolated" },
        { k: "Secrets", v: "never sent" },
      ],
      steps: ["classify task", "select runtime", "run tools"],
    },
    workflow: {
      index: "02",
      tag: "Workflow",
      title: "A workflow you can inspect",
      body: "DJL breaks work into clear steps. See the plan, watch each tool run, and review every change before it is applied.",
      steps: [
        {
          k: "Plan",
          v: "Work is decomposed into ordered, legible steps you can read before anything runs.",
        },
        {
          k: "Tools",
          v: "Each tool executes in a sandbox, streaming its output so nothing happens off-screen.",
        },
        {
          k: "Review",
          v: "Every diff waits for your approval. Apply, request changes, or roll back.",
        },
      ],
    },
    bilingual: {
      index: "03",
      tag: "Bilingual",
      title: "English and 中文, in one context",
      body: "DJL keeps both languages in view. Speak or type either one; the agent holds a single shared understanding of the task.",
      en: [
        "Create a new user endpoint with validation and tests.",
        "Add input validation using Zod.",
        "Write tests for success and failure cases.",
      ],
      zh: [
        "创建一个带有校验和测试的用户接口。",
        "使用 Zod 添加输入校验。",
        "为成功和失败场景编写测试。",
      ],
    },
    stack: {
      index: "04",
      tag: "Stack",
      title: "Plugs into your stack",
      body: "DJL drives the tools you already run: language toolchains, runtimes, editors, and model providers, local or online.",
      caption: "Drag to rotate / hover to steer",
    },
    pipeline: {
      index: "05",
      tag: "Pipeline",
      title: "From prototype to production",
      body: "Keep one flow from first experiment to shipped change. DJL plugs into the tools you already run.",
      steps: [
        { k: "Prototype", v: "explore & build" },
        { k: "Integrate", v: "use your tools" },
        { k: "Review", v: "approve with confidence" },
        { k: "Ship", v: "merge & deploy" },
      ],
    },
    cta: {
      tag: "READY",
      title: "Wake DJL",
      body: "Open your workspace and put an agent to work on your machine, in your language.",
      primary: "Open workspace",
      secondary: "Read the docs",
    },
    footer: {
      brand: "DJL",
      tag: "local-first agent command center",
      status: "STANDBY",
      cols: [
        { h: "Product", links: ["Routing", "Workflow", "Bilingual", "Pipeline"] },
        { h: "Resources", links: ["Docs", "Changelog", "Privacy", "Status"] },
      ],
      note: "Runs where you are.",
    },
    start: {
      tag: "GET STARTED",
      // Rendered by LayoutTextFlip: `text` is static, `words` rotate. Each word has to read as a
      // grammatical ending to `text` on its own.
      flip: {
        text: "Three steps to an agent that runs",
        words: ["privately", "on your own hardware", "without the cloud"],
      },
      body: "Install DJL, give it a model that runs on your own hardware, and keep approval over every change.",
      steps: [
        { k: "Install DJL", v: "One download for macOS or Windows." },
        { k: "Add a local model", v: "DJL detects your hardware and installs the runtime for you." },
        { k: "Describe a task", v: "Read the plan, watch the tools, approve the diff." },
      ],
      cta: "Read the guide",
    },
    guide: {
      eyebrow: "Guide",
      title: "Put DJL to work",
      lede: "Two things worth knowing: how the agent runs a task, and how to give it a model that runs on your own machine.",
      home: "Home",
      toc: "On this page",
      resources: "Resources",
      sections: { use: "Using the agent", local: "Installing a local model" },
      use: {
        index: "01",
        tag: "Using the agent",
        title: "Describe the task, then stay in control",
        body: "DJL turns a request into ordered steps, runs each tool in the open, and stops for your approval before anything touches your files.",
        steps: [
          {
            k: "Describe the task",
            v: "Write what you want in English or 中文. Both languages share one context, so you can switch mid-task without repeating yourself.",
          },
          {
            k: "Read the plan",
            v: "Work is decomposed into ordered, legible steps you can read before anything runs.",
          },
          {
            k: "Watch the tools",
            v: "Each tool executes in a sandbox, streaming its output so nothing happens off-screen.",
          },
          {
            k: "Review the diff",
            v: "Every change waits for you: approve and apply, request changes, or cancel and roll back.",
          },
        ],
        note: "Nothing reaches your project until you approve it.",
      },
      local: {
        index: "02",
        tag: "Installing a local model",
        title: "Run a model on your own hardware",
        body: "DJL works out what your computer can run, then installs and starts the runtime itself. No terminal, no admin password.",
        desktopOnly: "Local model management lives in the DJL desktop app.",
        steps: [
          { k: "Open the desktop app", v: "Download DJL for your platform and launch it." },
          {
            k: "Go to Settings → Local Models",
            v: "Listed under Private inference.",
          },
          {
            k: "Check what DJL detected",
            v: "It reports your processor, graphics card, and memory, then recommends the largest model that will still feel fast — deliberately one tier below what your machine could merely hold.",
          },
          {
            k: "Install and start a runtime",
            v: "Choose Ollama or LM Studio. DJL downloads it, starts the local server, and connects to it.",
          },
          {
            k: "Select the model",
            v: "Once installed, pick it in the model picker and describe your first task.",
          },
        ],
        runtimeTitle: "Two runtimes",
        runtimes: [
          {
            k: "Ollama",
            v: "DJL installs, starts, and connects Ollama for you. No terminal or admin password needed.",
          },
          {
            k: "LM Studio",
            v: "Install LM Studio once, then DJL can start and manage its local server.",
          },
        ],
        table: {
          title: "Curated models",
          caption: "DJL recommends one of these from your hardware. You can always choose another.",
          model: "Model",
          memory: "Memory",
          download: "Download",
          drives: "Drives the agent",
          yes: "Yes",
          no: "Chat only",
        },
        warning: {
          title: "“Chat only” means chat only",
          body: "Qwen3 1.7B and Qwen3.5 2B answer questions well but are too small to hold a tool-calling loop together. Give either one a task that needs file edits and it stalls silently instead of reporting an error. For real work pick a model marked “Drives the agent” — Granite 4.1 3B is the smallest that qualifies, and it runs in 8 GB.",
        },
        context: {
          title: "If the tools stop working",
          body: "A capable model still needs enough context loaded to use tools. When DJL says the model is chat-only at its current context, reload it with a larger context window and the tools come back.",
        },
        custom: {
          title: "Bringing your own model",
          body: "The curated list is a starting point, not a limit. Install any Ollama tag, LM Studio catalog ID, or exact Hugging Face model URL.",
        },
        privacy: {
          title: "What stays on your machine",
          body: "Inference runs locally: prompts, code context, and output are never sent to a hosted model provider. DJL connects only to fixed loopback addresses (127.0.0.1) and never exposes either runtime to your network. Tools you approve can still reach the network on their own.",
        },
      },
      cta: {
        title: "Ready when you are",
        body: "Download DJL and give it a model that runs where you are.",
        download: "Download for macOS",
      },
    },
    changelog: {
      eyebrow: "Changelog",
      title: "Every release, as it shipped",
      lede: "Read straight from the published GitHub releases. New versions appear here on their own, with no edit to this site.",
      home: "Home",
      guide: "Guide",
      current: "Current",
      prerelease: "Pre-release",
      published: "Published",
      viewOnGithub: "View release on GitHub",
      empty: "No releases have been published yet.",
      emptyHint: "The release feed could not be read just now. GitHub has the canonical list.",
      emptyAction: "Open releases on GitHub",
      // Stated rather than hidden: the notes are the tag annotation, so they cannot be translated at
      // render time without inventing content.
      sourceNote:
        "Release notes are taken from each version's GitHub release, so they appear in English.",
    },
    // Redesigned landing surface — paper-white system per design.md.
    landing: {
      nav: {
        product: "Product",
        capabilities: "Capabilities",
        localAi: "Local AI",
        docs: "Docs",
        download: "Download",
        menuLabel: "Menu",
        languageLabel: "English",
        githubLabel: "DJL on GitHub",
      },
      hero: {
        eyebrow: "DJL FOR DESKTOP",
        titleLines: ["A capable agent,", "on your desktop."],
        subhead:
          "Describe the outcome. DJL plans the work, uses the right tools, and pauses when your judgment matters.",
        downloadMac: "Download for macOS",
        downloadWindows: "Download for Windows",
        secondary: "View the product",
        caption: "macOS 13+ · Windows available",
        screenshotAlt: "The DJL desktop app",
      },
      demo: {
        windowTitle: "New Chat",
        handOff: "Hand off",
        tabs: { work: "Work", projects: "Projects" },
        newTask: "New task",
        writingCheck: "AI Writing Check",
        search: "Search",
        workLabel: "Work",
        noTasks: "No tasks yet",
        noProjects: "No projects yet",
        tutorial: "New user tutorial",
        settings: "Settings",
        headline: "What should we work on?",
        placeholder: "What do you want DJL to help you with?",
        fullAccess: "Full access",
        effort: "High",
        workFolder: "Managed Work folder",
        menus: {
          accessTitle: "How should actions be approved?",
          ask: "Ask for approval",
          askDesc: "Always ask to edit external files and use the internet",
          auto: "Approve for me",
          autoDesc: "Only ask for actions detected as potentially unsafe",
          fullDesc: "Unrestricted access to the internet and any file on your computer",
          variantTitle: "Variant",
          variants: ["Low (default)", "Medium", "High", "Max"],
          variantShort: ["Low", "Medium", "High", "Max"],
          assisted: "Assisted tools",
          chatOnly: "Chat only",
        },
        suggestions: [
          "Rename every .jpeg in this folder to .jpg",
          "Summarize this week's meeting notes",
          "Find the bug in utils.py",
        ],
        run: {
          stages: ["Plan", "Process", "Review", "Done"],
          planning: "Planning the work…",
          planLines: ["Scanning the Work folder", "3 steps planned"],
          toolLine: "tool · list_files",
          toolOutput: "12 files · 4 need changes",
          ready: "Work is ready for review",
          diff: "4 files changed",
          approve: "Approve",
          requestChanges: "Request changes",
          applied: "Applied. Task complete.",
          changesPrompt: "Tell me what you'd like changed.",
        },
      },
      product: {
        eyebrow: "Product",
        title: "One window. The whole loop.",
        body: "Plan, tools, diff, review — the entire run is visible in a single desktop window, and nothing is applied until you approve it.",
        manifesto: "Describe the outcome. Watch the work. Approve the change.",
        screenshotAlt: "A DJL task from plan to approved change",
      },
      capabilities: {
        eyebrow: "Capabilities",
        title: "Your work. Any model.",
        cards: [
          {
            title: "Speak naturally",
            body: "Use multiple languages in one task. Change language mid-sentence and DJL keeps the same working context.",
          },
          {
            title: "Switch models, keep context",
            body: "Move to a different model in one click. Your task, files, and instructions stay exactly where they are.",
          },
          {
            title: "API to fully local",
            body: "Reach hosted models when you need them, or run privately through Ollama and LM Studio on your own machine.",
          },
          {
            title: "Light or dark",
            body: "Follow your system or choose the appearance that keeps long work sessions comfortable.",
          },
        ],
      },
      localAi: {
        eyebrow: "Local AI",
        title: "Actually local.",
        body: "Pick a model sized to your hardware and DJL runs it on-device — planning, tool calls and edits included.",
        bullets: [
          "Runs with the network cable out",
          "Curated models from 1.7B to 30B",
          "Memory requirements stated up front",
        ],
      },
      runtimes: {
        eyebrow: "Local vs API",
        title: "Why an API model is still the workhorse",
        body: "Local models earn their place — but bigger tasks want a bigger brain. Here is the honest comparison, and how DJL lets you use both.",
        api: {
          tag: "Frontier capability",
          title: "API model",
          points: [
            "Frontier-level reasoning — plans further ahead and untangles harder bugs than anything that fits in local memory",
            "Long context: holds far more of your codebase in one task",
            "Full speed on any machine — inference runs in the datacenter, not on your fans",
            "Dependable tool-driving, from the first call to the last diff",
          ],
          note: "Routed over a secure connection — and only when you choose.",
        },
        local: {
          tag: "Private by default",
          title: "Local model",
          pros: ["Code never leaves the device", "Works offline; nothing to pay per token"],
          cons: [
            "Capability tops out at 30B — frontier models are a league above",
            "Wants 4–32 GB of memory; the best local models need the biggest machines",
            "The smallest models chat but can't drive tools",
          ],
        },
        closing:
          "The DJL answer: run both. Keep private, everyday work local — and when the task is bigger than the machine, route it to the API. Every change is review-gated either way, and your keys stay home.",
      },
      faq: {
        eyebrow: "FAQ",
        title: "Frequently asked questions",
        items: [
          {
            q: "Which platforms does DJL run on?",
            a: "macOS 13 and newer, on both Apple Silicon and Intel, plus Windows. Every download button fetches the newest published release.",
          },
          {
            q: "Does my code leave my machine?",
            a: "Not unless you choose to. Local models run entirely on-device — prompts, code context, and output are never sent to a hosted provider. Routing a task to an online runtime is always an explicit choice you make.",
          },
          {
            q: "Does DJL work offline?",
            a: "With a local model installed, yes — planning, tool calls, and edits all run on-device, network cable out. The network is only involved when you route a task to an online runtime.",
          },
          {
            q: "What hardware do local models need?",
            a: "The curated catalog spans 1.7B to 30B parameters, and every model states its memory requirement up front — from 4 GB for the smallest to 32 GB for the largest.",
          },
          {
            q: "Do all local models drive tools?",
            a: "No — the smallest models in the catalog chat but don't drive tools. The catalog marks which models are agent-capable, so you know before installing one.",
          },
          {
            q: "What can the agent actually do on my machine?",
            a: "It works through 14 registered tools — reading and editing files, running commands, and more. Every tool runs sandboxed with streamed output, so nothing happens off-screen.",
          },
          {
            q: "Can I mix Chinese and English in one task?",
            a: "Yes. 中文 and English share one context — switch language mid-task and the agent keeps up, without restating anything.",
          },
          {
            q: "How are file changes and secrets handled?",
            a: "Every change waits for your review before it lands, and keys stay on your machine — they are never sent to any runtime.",
          },
          {
            q: "How do updates ship?",
            a: "Through GitHub releases. New versions are published on the official feed, and the changelog page reads straight from the published releases.",
          },
        ],
        moreQuestions: "More questions?",
        guideLink: "Read the guide",
        githubLink: "Ask on GitHub",
      },
      ctaStrip: {
        title: "Put an agent on your desktop.",
        button: "Download DJL",
      },
      footer: {
        download: "Download",
        docs: "Docs",
        changelog: "Changelog",
        github: "GitHub",
        copyright: "© 2026 DJL",
      },
    },
  },

  zh: {
    htmlLang: "zh-CN",
    dir: "双语智能体命令中心",
    nav: [
      { id: "routing", label: "路由" },
      { id: "workflow", label: "流程" },
      { id: "bilingual", label: "双语" },
      { id: "stack", label: "生态" },
      { id: "pipeline", label: "流水线" },
    ],
    getStarted: "打开工作区",
    enterHint: "按任意键进入",
    skip: "跳过开场",
    boot: {
      brand: "DJL",
      label: "本地运行时",
      lines: [
        { text: "正在初始化 DJL 内核" },
        { text: "挂载本地运行时", ok: true },
        { text: "模型: deepseek-v4-flash", ok: true },
        { text: "工具: 已注册 14 个", ok: true },
        { text: "工作区: 已隔离且私密", ok: true },
        { text: "在线通道: 待命" },
        { text: "校准意图路由器" },
      ] as BootLine[],
      ready: "智能体已唤醒",
    },
    hero: {
      status: "本地 / 在线就绪",
      coord: "EN / 中文",
      kicker: "在你所在之处运行的智能",
      titleLines: ["在你的设备上", "唤醒智能体。"],
      body: "DJL 是面向构建者的双语命令中心。在本地与在线运行时之间路由每个任务，观察每个工具运行，并在变更落地前逐一批准。",
      primary: "打开工作区",
      secondary: "阅读文档",
      stats: [
        { k: "本地优先", v: "默认私密" },
        { k: "14 个工具", v: "已注册 · 已隔离" },
        { k: "EN / 中文", v: "同一上下文" },
        { k: "审查门控", v: "每一次变更" },
      ],
      hud: {
        model: "模型",
        modelValue: "DJL-CORE",
        state: "状态",
        stateValue: "已唤醒",
      },
    },
    field: {
      depthLabel: "深度",
      descend: "向下进入运行栈",
      strata: ["界面", "路由", "流程", "双语", "生态", "流水线", "内核"],
      glyphs: [
        "› 路由 → 本地",
        "工具 · read_file ✓",
        "内核 · deepseek-v4-flash",
        "意图已分类",
        "变更 · 等待审查",
        "沙箱 · 已隔离",
        "EN ↔ 中文",
        "run tests ✓",
      ],
    },
    console: {
      tag: "实时会话",
      task: "构建带校验和测试的用户接口",
      state: "进行中",
      tabs: [
        { id: "plan" as ConsoleTab, label: "计划" },
        { id: "tools" as ConsoleTab, label: "工具" },
        { id: "review" as ConsoleTab, label: "审查" },
      ],
      timeline: [
        ["计划", "创建步骤"],
        ["工具", "运行已选工具"],
        ["读取", "src/routes/users.ts"],
        ["编辑", "src/routes/users.ts"],
        ["测试", "npm test"],
        ["审查", "等待你的批准"],
      ],
      file: "src/routes/users.ts",
      terminal: { cmd: "npm test", pass: "PASS", file: "tests/users.test.ts" },
      tests: ["创建用户 (23 ms)", "校验邮箱 (18 ms)"],
      testSummary: "2 项通过 · 541 ms",
      review: {
        title: "审查变更",
        action: "编辑文件",
        summaryLabel: "摘要",
        summary: "新增 POST /users 接口，并包含校验与测试。",
        impactLabel: "影响",
        impact: ["新增路由", "新增输入校验", "新增测试"],
        filesLabel: "文件",
        files: ["src/routes/users.ts", "tests/users.test.ts"],
        approve: "批准并应用",
        request: "请求修改",
        cancel: "取消 / 回滚",
      },
    },
    routing: {
      index: "01",
      tag: "路由",
      title: "为每个任务选择运行位置",
      body: "根据敏感度与速度，把任务路由到本地或在线运行时。代码与数据始终留在你设定的边界内。",
      workspace: "你的工作区",
      router: "DJL 路由器",
      local: "本地",
      online: "在线",
      localBody: "默认私密。数据不会离开设备。",
      onlineBody: "适合扩展。仅使用安全连接。",
      items: [
        { k: "文件", v: "限定于项目" },
        { k: "环境", v: "已隔离" },
        { k: "密钥", v: "从不外发" },
      ],
      steps: ["分类任务", "选择运行时", "运行工具"],
    },
    workflow: {
      index: "02",
      tag: "流程",
      title: "可被检查的工作流程",
      body: "DJL 把工作拆成清晰步骤。查看计划、观察每个工具运行，并在应用前审查每个变更。",
      steps: [
        { k: "计划", v: "工作被拆解为有序、可读的步骤，运行前你就能看清。" },
        { k: "工具", v: "每个工具在沙箱中执行并实时输出，没有任何动作发生在视线之外。" },
        { k: "审查", v: "每个差异都等待你的批准：应用、请求修改，或回滚。" },
      ],
    },
    bilingual: {
      index: "03",
      tag: "双语",
      title: "English 与中文，同一上下文",
      body: "DJL 让两种语言同时在场。用任意一种说或写，智能体始终保持对任务的同一份理解。",
      en: [
        "Create a new user endpoint with validation and tests.",
        "Add input validation using Zod.",
        "Write tests for success and failure cases.",
      ],
      zh: [
        "创建一个带有校验和测试的用户接口。",
        "使用 Zod 添加输入校验。",
        "为成功和失败场景编写测试。",
      ],
    },
    stack: {
      index: "04",
      tag: "生态",
      title: "接入你的技术栈",
      body: "DJL 驱动你已经在用的工具：语言工具链、运行时、编辑器与模型提供方，本地或在线。",
      caption: "拖动旋转 / 悬停转向",
    },
    pipeline: {
      index: "05",
      tag: "流水线",
      title: "从原型到生产",
      body: "从第一次实验到上线变更，保持同一套流程。DJL 接入你已经在用的工具。",
      steps: [
        { k: "原型", v: "探索并构建" },
        { k: "集成", v: "使用你的工具" },
        { k: "审查", v: "放心批准" },
        { k: "上线", v: "合并并部署" },
      ],
    },
    cta: {
      tag: "就绪",
      title: "唤醒 DJL",
      body: "打开工作区，让智能体在你的设备上用你的语言开始工作。",
      primary: "打开工作区",
      secondary: "阅读文档",
    },
    footer: {
      brand: "DJL",
      tag: "本地优先的智能体命令中心",
      status: "待命",
      cols: [
        { h: "产品", links: ["路由", "流程", "双语", "流水线"] },
        { h: "资源", links: ["文档", "更新日志", "隐私", "状态"] },
      ],
      note: "在你所在之处运行。",
    },
    start: {
      tag: "开始使用",
      flip: {
        text: "三步拥有一个智能体，它运行在",
        words: ["你的设备上", "本地", "你自己的硬件上"],
      },
      body: "安装 DJL，为它配置一个在你自己硬件上运行的模型，并对每一次改动保留批准权。",
      steps: [
        { k: "安装 DJL", v: "macOS 与 Windows 各一个安装包。" },
        { k: "添加本地模型", v: "DJL 会检测你的硬件并自动安装运行时。" },
        { k: "描述任务", v: "阅读计划、观察工具、批准差异。" },
      ],
      cta: "阅读指南",
    },
    guide: {
      eyebrow: "指南",
      title: "让 DJL 开始工作",
      lede: "两件值得了解的事：智能体如何执行一项任务，以及如何为它配置一个在你自己设备上运行的模型。",
      home: "首页",
      toc: "本页内容",
      resources: "资源",
      sections: { use: "使用智能体", local: "安装本地模型" },
      use: {
        index: "01",
        tag: "使用智能体",
        title: "描述任务，并始终掌控",
        body: "DJL 会把请求拆解为有序步骤，公开运行每个工具，并在改动触及你的文件之前停下来等待批准。",
        steps: [
          {
            k: "描述任务",
            v: "用中文或英文写下你的需求。两种语言共享同一上下文，因此可以中途切换而无需重述。",
          },
          {
            k: "阅读计划",
            v: "工作会被拆解为有序、清晰的步骤，在任何操作运行之前供你阅读。",
          },
          {
            k: "观察工具",
            v: "每个工具都在沙箱中执行，并实时输出，任何事都不会在你看不到的地方发生。",
          },
          {
            k: "审查差异",
            v: "每一处改动都会等你决定：批准并应用、要求修改，或取消并回滚。",
          },
        ],
        note: "在你批准之前，任何内容都不会写入你的项目。",
      },
      local: {
        index: "02",
        tag: "安装本地模型",
        title: "在你自己的硬件上运行模型",
        body: "DJL 会判断你的电脑能够运行什么，然后自行安装并启动运行时。无需终端，也无需管理员密码。",
        desktopOnly: "本地模型管理位于 DJL 桌面应用中。",
        steps: [
          { k: "打开桌面应用", v: "下载对应平台的 DJL 并启动。" },
          { k: "进入设置 → 本地模型", v: "位于「私有推理」分组下。" },
          {
            k: "查看 DJL 的检测结果",
            v: "它会报告你的处理器、显卡与内存，并推荐仍能保持流畅的最大模型——有意比你的机器勉强装得下的规格低一档。",
          },
          {
            k: "安装并启动运行时",
            v: "选择 Ollama 或 LM Studio。DJL 会完成下载、启动本地服务并建立连接。",
          },
          {
            k: "选择模型",
            v: "安装完成后，在模型选择器中选中它，然后描述你的第一个任务。",
          },
        ],
        runtimeTitle: "两种运行时",
        runtimes: [
          {
            k: "Ollama",
            v: "DJL 会为你安装、启动并连接 Ollama。无需终端或管理员密码。",
          },
          {
            k: "LM Studio",
            v: "只需安装一次 LM Studio，之后 DJL 即可启动并管理它的本地服务。",
          },
        ],
        table: {
          title: "精选模型",
          caption: "DJL 会依据你的硬件推荐其中之一，你也随时可以另选。",
          model: "模型",
          memory: "内存",
          download: "下载体积",
          drives: "可驱动智能体",
          yes: "可以",
          no: "仅对话",
        },
        warning: {
          title: "「仅对话」就是只能对话",
          body: "Qwen3 1.7B 与 Qwen3.5 2B 回答问题不错，但太小，无法完整维持一轮工具调用循环。若交给它们需要修改文件的任务，它们会静默停滞而不会报错。要做实际工作，请选择标记为「可驱动智能体」的模型——Granite 4.1 3B 是其中最小的一个，8 GB 内存即可运行。",
        },
        context: {
          title: "如果工具失效了",
          body: "即使模型本身够强，也需要加载足够的上下文才能使用工具。当 DJL 提示当前上下文下仅能对话时，请以更大的上下文窗口重新加载该模型，工具便会恢复。",
        },
        custom: {
          title: "使用你自己的模型",
          body: "精选列表只是起点，而非限制。你可以安装任意 Ollama 标签、LM Studio 目录 ID，或精确的 Hugging Face 模型链接。",
        },
        privacy: {
          title: "哪些内容留在你的设备上",
          body: "推理在本地进行：提示词、代码上下文与输出都不会发送给托管的模型服务商。DJL 只连接固定的本地回环地址（127.0.0.1），绝不会把任一运行时暴露到你的网络中。你批准的工具仍可自行访问网络。",
        },
      },
      cta: {
        title: "随时可以开始",
        body: "下载 DJL，为它配置一个在你所在之处运行的模型。",
        download: "下载 macOS 版",
      },
    },
    changelog: {
      eyebrow: "更新日志",
      title: "每一个发布版本",
      lede: "内容直接来自 GitHub 上已发布的版本。新版本会自动出现在这里，无需改动本站。",
      home: "首页",
      guide: "指南",
      current: "当前版本",
      prerelease: "预发布",
      published: "发布于",
      viewOnGithub: "在 GitHub 上查看",
      empty: "尚未发布任何版本。",
      emptyHint: "暂时无法读取发布列表。GitHub 上有完整的版本记录。",
      emptyAction: "在 GitHub 上查看发布",
      sourceNote: "更新日志取自各版本的 GitHub 发布说明，因此以英文呈现。",
    },
    // 重构后的落地页 —— design.md 纸白设计系统。
    landing: {
      nav: {
        product: "产品",
        capabilities: "能力",
        localAi: "本地 AI",
        docs: "文档",
        download: "下载",
        menuLabel: "菜单",
        languageLabel: "中文",
        githubLabel: "DJL 的 GitHub 仓库",
      },
      hero: {
        eyebrow: "DJL 桌面版",
        titleLines: ["能独当一面的智能体，", "就在你的桌面上。"],
        subhead: "描述你想要的结果。DJL 规划任务、调用合适的工具，并在需要你判断的时刻停下来等你。",
        downloadMac: "下载 macOS 版",
        downloadWindows: "下载 Windows 版",
        secondary: "了解产品",
        caption: "macOS 13+ · 同时支持 Windows",
        screenshotAlt: "DJL 桌面应用界面",
      },
      demo: {
        windowTitle: "新对话",
        handOff: "移交",
        tabs: { work: "工作", projects: "项目" },
        newTask: "新任务",
        writingCheck: "AI 写作检测",
        search: "搜索",
        workLabel: "工作",
        noTasks: "暂无任务",
        noProjects: "暂无项目",
        tutorial: "新手教程",
        settings: "设置",
        headline: "我们来做点什么？",
        placeholder: "想让 DJL 帮你做什么？",
        fullAccess: "完全访问",
        effort: "高",
        workFolder: "托管工作文件夹",
        menus: {
          accessTitle: "如何批准操作？",
          ask: "请求批准",
          askDesc: "编辑外部文件与访问网络时总是询问",
          auto: "替我批准",
          autoDesc: "仅在检测到潜在不安全的操作时询问",
          fullDesc: "不受限制地访问网络与你计算机上的任何文件",
          variantTitle: "变体",
          variants: ["低（默认）", "中", "高", "最高"],
          variantShort: ["低", "中", "高", "最高"],
          assisted: "辅助工具",
          chatOnly: "仅对话",
        },
        suggestions: [
          "把这个文件夹里的 .jpeg 全部改名为 .jpg",
          "总结本周的会议记录",
          "找出 utils.py 里的 bug",
        ],
        run: {
          stages: ["规划", "处理", "检查", "完成"],
          planning: "正在规划…",
          planLines: ["正在扫描工作文件夹", "已规划 3 个步骤"],
          toolLine: "tool · list_files",
          toolOutput: "12 个文件 · 4 个需要修改",
          ready: "工作已就绪，等待审查",
          diff: "4 个文件已修改",
          approve: "批准",
          requestChanges: "请求更改",
          applied: "已应用，任务完成。",
          changesPrompt: "告诉我需要调整什么。",
        },
      },
      product: {
        eyebrow: "产品",
        title: "一个窗口，完整闭环。",
        body: "计划、工具、差异、审查——整个执行过程在一个桌面窗口里清晰可见，未经你批准不落地任何变更。",
        manifesto: "描述结果。看它做事。批准变更。",
        screenshotAlt: "DJL 任务从计划到批准的完整过程",
      },
      capabilities: {
        eyebrow: "能力",
        title: "你的工作，适配每一种模型。",
        cards: [
          {
            title: "自然使用多种语言",
            body: "在同一个任务中使用多种语言。即使中途切换，DJL 也会保留完整的工作上下文。",
          },
          {
            title: "切换模型，上下文不断",
            body: "一键换到更合适的模型，当前任务、文件和指令都会留在原位。",
          },
          {
            title: "从 API 到完全本地",
            body: "需要更强能力时连接 API，也可以通过 Ollama 与 LM Studio 在自己的设备上私密运行。",
          },
          {
            title: "深色或浅色",
            body: "跟随系统，也可以手动选择更适合长时间工作的外观。",
          },
        ],
      },
      localAi: {
        eyebrow: "本地 AI",
        title: "真正在本地。",
        body: "按你的硬件选择合适规模的模型，DJL 在设备上完成规划、调用工具与修改代码。",
        bullets: ["拔掉网线也能运行", "1.7B 到 30B 的精选模型", "内存需求提前写明"],
      },
      runtimes: {
        eyebrow: "本地 vs API",
        title: "为什么 API 模型依然是主力",
        body: "本地模型有它的位置——但更大的任务需要更大的大脑。这里是一份诚实的对比，以及 DJL 如何让你两者兼得。",
        api: {
          tag: "前沿能力",
          title: "API 模型",
          points: [
            "前沿级推理——比任何装得进本地内存的模型看得更远、解得开更难的问题",
            "超长上下文：一次任务能装下更多的代码库内容",
            "任何设备都全速运行——推理在数据中心完成，而不是靠你的风扇",
            "从第一次调用到最后一个差异，工具驱动始终可靠",
          ],
          note: "通过安全连接路由——且只在你选择时。",
        },
        local: {
          tag: "默认私密",
          title: "本地模型",
          pros: ["代码不出设备", "离线可用，没有按 token 计费"],
          cons: [
            "能力上限在 30B——前沿模型高出一个量级",
            "需要 4–32 GB 内存；最强的本地模型要配最强的机器",
            "最小的模型只能对话，不能驱动工具",
          ],
        },
        closing:
          "DJL 的答案：两个都用。私密的日常工作留在本地——当任务超出机器的能力时，路由给 API。无论哪条路，每个变更都要经你审查，密钥永远留在本机。",
      },
      faq: {
        eyebrow: "FAQ",
        title: "常见问题",
        items: [
          {
            q: "DJL 支持哪些平台？",
            a: "macOS 13 及以上（Apple Silicon 与 Intel 均可），以及 Windows。每个下载按钮都会获取最新发布的版本。",
          },
          {
            q: "我的代码会离开我的设备吗？",
            a: "除非你主动选择，否则不会。本地模型完全在设备上运行——提示词、代码上下文与输出不会发送给任何托管服务商。把任务路由到在线运行时永远是你的显式选择。",
          },
          {
            q: "DJL 能离线使用吗？",
            a: "装好本地模型后可以——规划、调用工具与修改代码都在设备上完成，拔掉网线也能运行。只有当你把任务路由给在线运行时，才会用到网络。",
          },
          {
            q: "本地模型需要什么硬件？",
            a: "精选目录覆盖 1.7B 到 30B 参数规模，每个模型都提前写明内存需求——最小 4 GB，最大 32 GB。",
          },
          {
            q: "所有本地模型都能驱动工具吗？",
            a: "不是——目录中最小的几个模型只能对话，不能驱动工具。目录会标明哪些模型具备智能体能力，安装前一目了然。",
          },
          {
            q: "智能体在我的设备上究竟能做什么？",
            a: "它通过 14 个已注册工具工作——读写文件、执行命令等。每个工具都在沙箱中运行、实时输出，没有任何事发生在屏幕之外。",
          },
          {
            q: "同一个任务里能中英文混用吗？",
            a: "可以。中文与 English 共享同一上下文——任务中途切换语言，智能体照样跟得上，无需重复说明。",
          },
          {
            q: "文件变更和密钥如何处理？",
            a: "每一个变更都要等你审查后才会落地；密钥保存在你的设备上，永远不会发送给任何运行时。",
          },
          {
            q: "如何获取更新？",
            a: "通过 GitHub 发布。新版本发布在官方发布源上，更新日志页面直接读取已发布的版本。",
          },
        ],
        moreQuestions: "还有疑问？",
        guideLink: "阅读指南",
        githubLink: "在 GitHub 上提问",
      },
      ctaStrip: {
        title: "把智能体装进你的桌面。",
        button: "下载 DJL",
      },
      footer: {
        download: "下载",
        docs: "文档",
        changelog: "更新日志",
        github: "GitHub",
        copyright: "© 2026 DJL",
      },
    },
  },
} as const;

export type Content = (typeof content)[Locale];
