export type Locale = "en" | "zh";
export type ConsoleTab = "plan" | "tools" | "review";

type BootLine = { text: string; ok?: boolean };

export const codeLines = [
  "import { Router } from 'express'",
  "import { z } from 'zod'",
  "import { createUser } from '../lib/user'",
  "",
  "const router = Router()",
  "const Body = z.object({",
  "  name: z.string().min(1),",
  "  email: z.string().email(),",
  "})",
  "",
  "router.post('/users', async (req, res) => {",
  "  const parsed = Body.safeParse(req.body)",
  "  if (!parsed.success) {",
  "    return res.status(400).json({ error: 'Invalid input' })",
  "  }",
  "  const user = await createUser(parsed.data)",
  "  res.status(201).json(user)",
  "})",
];

// simple-icons slugs rendered white into the Icon Cloud: the runtimes,
// languages, editors and providers DJL drives.
export const iconSlugs = [
  "typescript",
  "javascript",
  "python",
  "rust",
  "go",
  "react",
  "nextdotjs",
  "nodedotjs",
  "docker",
  "git",
  "github",
  "githubcopilot",
  "ollama",
  "huggingface",
  "pytorch",
  "postgresql",
  "redis",
  "linux",
  "apple",
  "neovim",
];

export const iconImages = iconSlugs.map((s) => `https://cdn.simpleicons.org/${s}/0b1118`);

export const content = {
  en: {
    htmlLang: "en",
    dir: "Bilingual agent command center",
    nav: [
      { id: "routing", label: "Routing" },
      { id: "workflow", label: "Workflow" },
      { id: "bilingual", label: "Bilingual" },
      { id: "stack", label: "Stack" },
      { id: "pipeline", label: "Pipeline" },
    ],
    getStarted: "Open workspace",
    enterHint: "press any key to enter",
    skip: "skip intro",
    boot: {
      brand: "DJL",
      label: "LOCAL RUNTIME",
      lines: [
        { text: "initializing DJL kernel" },
        { text: "mounting local runtime", ok: true },
        { text: "model: deepseek-v4-flash", ok: true },
        { text: "tools: 14 registered", ok: true },
        { text: "workspace: scoped and private", ok: true },
        { text: "online bridge: standby" },
        { text: "calibrating intent router" },
      ] as BootLine[],
      ready: "AGENT AWAKE",
    },
    hero: {
      status: "LOCAL / ONLINE READY",
      coord: "EN / 中文",
      kicker: "An intelligence that runs where you are",
      titleLines: ["Agent wakes", "on your machine."],
      body: "Run a bilingual coding agent locally, route tasks online when needed, and approve every file change before it lands.",
      primary: "Open workspace",
      secondary: "Read the docs",
      stats: [
        { k: "Local-first", v: "private by default" },
        { k: "14 tools", v: "registered & sandboxed" },
        { k: "EN / 中文", v: "one shared context" },
        { k: "Review-gated", v: "every change" },
      ],
      hud: {
        model: "MODEL",
        modelValue: "DJL-CORE",
        state: "STATE",
        stateValue: "AWAKE",
      },
    },
    field: {
      depthLabel: "DEPTH",
      descend: "descend the stack",
      strata: ["SURFACE", "ROUTER", "WORKFLOW", "BILINGUAL", "STACK", "PIPELINE", "KERNEL"],
      glyphs: [
        "› route → local",
        "tool · read_file ✓",
        "kernel · deepseek-v4-flash",
        "intent classified",
        "diff · awaiting review",
        "sandbox · scoped",
        "中文 ↔ EN",
        "运行测试 ✓",
      ],
    },
    console: {
      tag: "LIVE SESSION",
      task: "Build a user endpoint with validation and tests",
      state: "in progress",
      tabs: [
        { id: "plan" as ConsoleTab, label: "Plan" },
        { id: "tools" as ConsoleTab, label: "Tools" },
        { id: "review" as ConsoleTab, label: "Review" },
      ],
      timeline: [
        ["Plan", "create steps"],
        ["Tools", "run selected tools"],
        ["Read", "src/routes/users.ts"],
        ["Edit", "src/routes/users.ts"],
        ["Test", "npm test"],
        ["Review", "awaiting your approval"],
      ],
      file: "src/routes/users.ts",
      terminal: { cmd: "npm test", pass: "PASS", file: "tests/users.test.ts" },
      tests: ["creates a user (23 ms)", "validates email (18 ms)"],
      testSummary: "2 passed · 541 ms",
      review: {
        title: "Review change",
        action: "Edit file",
        summaryLabel: "Summary",
        summary: "Added POST /users with validation and tests.",
        impactLabel: "Impact",
        impact: ["adds new route", "adds input validation", "adds tests"],
        filesLabel: "Files",
        files: ["src/routes/users.ts", "tests/users.test.ts"],
        approve: "Approve & apply",
        request: "Request changes",
        cancel: "Cancel / rollback",
      },
    },
    routing: {
      index: "01",
      tag: "Routing",
      title: "Choose where every task runs",
      body: "Route work to local or online runtimes by sensitivity and speed. Your code and data stay scoped exactly where you put them.",
      workspace: "Your workspace",
      router: "DJL router",
      local: "Local",
      online: "Online",
      localBody: "Private by default. Nothing leaves the device.",
      onlineBody: "Best for reach. Secure connections only.",
      items: [
        { k: "Files", v: "scoped to project" },
        { k: "Environment", v: "isolated" },
        { k: "Secrets", v: "never sent" },
      ],
      steps: ["classify task", "select runtime", "run tools"],
    },
    workflow: {
      index: "02",
      tag: "Workflow",
      title: "A workflow you can inspect",
      body: "DJL breaks work into clear steps. See the plan, watch each tool run, and review every change before it is applied.",
      steps: [
        {
          k: "Plan",
          v: "Work is decomposed into ordered, legible steps you can read before anything runs.",
        },
        {
          k: "Tools",
          v: "Each tool executes in a sandbox, streaming its output so nothing happens off-screen.",
        },
        {
          k: "Review",
          v: "Every diff waits for your approval. Apply, request changes, or roll back.",
        },
      ],
    },
    bilingual: {
      index: "03",
      tag: "Bilingual",
      title: "English and 中文, in one context",
      body: "DJL keeps both languages in view. Speak or type either one; the agent holds a single shared understanding of the task.",
      en: [
        "Create a new user endpoint with validation and tests.",
        "Add input validation using Zod.",
        "Write tests for success and failure cases.",
      ],
      zh: [
        "创建一个带有校验和测试的用户接口。",
        "使用 Zod 添加输入校验。",
        "为成功和失败场景编写测试。",
      ],
    },
    stack: {
      index: "04",
      tag: "Stack",
      title: "Plugs into your stack",
      body: "DJL drives the tools you already run: language toolchains, runtimes, editors, and model providers, local or online.",
      caption: "Drag to rotate / hover to steer",
    },
    pipeline: {
      index: "05",
      tag: "Pipeline",
      title: "From prototype to production",
      body: "Keep one flow from first experiment to shipped change. DJL plugs into the tools you already run.",
      steps: [
        { k: "Prototype", v: "explore & build" },
        { k: "Integrate", v: "use your tools" },
        { k: "Review", v: "approve with confidence" },
        { k: "Ship", v: "merge & deploy" },
      ],
    },
    cta: {
      tag: "READY",
      title: "Wake DJL",
      body: "Open your workspace and put an agent to work on your machine, in your language.",
      primary: "Open workspace",
      secondary: "Read the docs",
    },
    footer: {
      brand: "DJL",
      tag: "local-first agent command center",
      status: "STANDBY",
      cols: [
        { h: "Product", links: ["Routing", "Workflow", "Bilingual", "Pipeline"] },
        { h: "Resources", links: ["Docs", "Changelog", "Privacy", "Status"] },
      ],
      note: "Runs where you are.",
    },
  },

  zh: {
    htmlLang: "zh-CN",
    dir: "双语智能体命令中心",
    nav: [
      { id: "routing", label: "路由" },
      { id: "workflow", label: "流程" },
      { id: "bilingual", label: "双语" },
      { id: "stack", label: "生态" },
      { id: "pipeline", label: "流水线" },
    ],
    getStarted: "打开工作区",
    enterHint: "按任意键进入",
    skip: "跳过开场",
    boot: {
      brand: "DJL",
      label: "本地运行时",
      lines: [
        { text: "正在初始化 DJL 内核" },
        { text: "挂载本地运行时", ok: true },
        { text: "模型: deepseek-v4-flash", ok: true },
        { text: "工具: 已注册 14 个", ok: true },
        { text: "工作区: 已隔离且私密", ok: true },
        { text: "在线通道: 待命" },
        { text: "校准意图路由器" },
      ] as BootLine[],
      ready: "智能体已唤醒",
    },
    hero: {
      status: "本地 / 在线就绪",
      coord: "EN / 中文",
      kicker: "在你所在之处运行的智能",
      titleLines: ["在你的设备上", "唤醒智能体。"],
      body: "DJL 是面向构建者的双语命令中心。在本地与在线运行时之间路由每个任务，观察每个工具运行，并在变更落地前逐一批准。",
      primary: "打开工作区",
      secondary: "阅读文档",
      stats: [
        { k: "本地优先", v: "默认私密" },
        { k: "14 个工具", v: "已注册 · 已隔离" },
        { k: "EN / 中文", v: "同一上下文" },
        { k: "审查门控", v: "每一次变更" },
      ],
      hud: {
        model: "模型",
        modelValue: "DJL-CORE",
        state: "状态",
        stateValue: "已唤醒",
      },
    },
    field: {
      depthLabel: "深度",
      descend: "向下进入运行栈",
      strata: ["界面", "路由", "流程", "双语", "生态", "流水线", "内核"],
      glyphs: [
        "› 路由 → 本地",
        "工具 · read_file ✓",
        "内核 · deepseek-v4-flash",
        "意图已分类",
        "变更 · 等待审查",
        "沙箱 · 已隔离",
        "EN ↔ 中文",
        "run tests ✓",
      ],
    },
    console: {
      tag: "实时会话",
      task: "构建带校验和测试的用户接口",
      state: "进行中",
      tabs: [
        { id: "plan" as ConsoleTab, label: "计划" },
        { id: "tools" as ConsoleTab, label: "工具" },
        { id: "review" as ConsoleTab, label: "审查" },
      ],
      timeline: [
        ["计划", "创建步骤"],
        ["工具", "运行已选工具"],
        ["读取", "src/routes/users.ts"],
        ["编辑", "src/routes/users.ts"],
        ["测试", "npm test"],
        ["审查", "等待你的批准"],
      ],
      file: "src/routes/users.ts",
      terminal: { cmd: "npm test", pass: "PASS", file: "tests/users.test.ts" },
      tests: ["创建用户 (23 ms)", "校验邮箱 (18 ms)"],
      testSummary: "2 项通过 · 541 ms",
      review: {
        title: "审查变更",
        action: "编辑文件",
        summaryLabel: "摘要",
        summary: "新增 POST /users 接口，并包含校验与测试。",
        impactLabel: "影响",
        impact: ["新增路由", "新增输入校验", "新增测试"],
        filesLabel: "文件",
        files: ["src/routes/users.ts", "tests/users.test.ts"],
        approve: "批准并应用",
        request: "请求修改",
        cancel: "取消 / 回滚",
      },
    },
    routing: {
      index: "01",
      tag: "路由",
      title: "为每个任务选择运行位置",
      body: "根据敏感度与速度，把任务路由到本地或在线运行时。代码与数据始终留在你设定的边界内。",
      workspace: "你的工作区",
      router: "DJL 路由器",
      local: "本地",
      online: "在线",
      localBody: "默认私密。数据不会离开设备。",
      onlineBody: "适合扩展。仅使用安全连接。",
      items: [
        { k: "文件", v: "限定于项目" },
        { k: "环境", v: "已隔离" },
        { k: "密钥", v: "从不外发" },
      ],
      steps: ["分类任务", "选择运行时", "运行工具"],
    },
    workflow: {
      index: "02",
      tag: "流程",
      title: "可被检查的工作流程",
      body: "DJL 把工作拆成清晰步骤。查看计划、观察每个工具运行，并在应用前审查每个变更。",
      steps: [
        { k: "计划", v: "工作被拆解为有序、可读的步骤，运行前你就能看清。" },
        { k: "工具", v: "每个工具在沙箱中执行并实时输出，没有任何动作发生在视线之外。" },
        { k: "审查", v: "每个差异都等待你的批准：应用、请求修改，或回滚。" },
      ],
    },
    bilingual: {
      index: "03",
      tag: "双语",
      title: "English 与中文，同一上下文",
      body: "DJL 让两种语言同时在场。用任意一种说或写，智能体始终保持对任务的同一份理解。",
      en: [
        "Create a new user endpoint with validation and tests.",
        "Add input validation using Zod.",
        "Write tests for success and failure cases.",
      ],
      zh: [
        "创建一个带有校验和测试的用户接口。",
        "使用 Zod 添加输入校验。",
        "为成功和失败场景编写测试。",
      ],
    },
    stack: {
      index: "04",
      tag: "生态",
      title: "接入你的技术栈",
      body: "DJL 驱动你已经在用的工具：语言工具链、运行时、编辑器与模型提供方，本地或在线。",
      caption: "拖动旋转 / 悬停转向",
    },
    pipeline: {
      index: "05",
      tag: "流水线",
      title: "从原型到生产",
      body: "从第一次实验到上线变更，保持同一套流程。DJL 接入你已经在用的工具。",
      steps: [
        { k: "原型", v: "探索并构建" },
        { k: "集成", v: "使用你的工具" },
        { k: "审查", v: "放心批准" },
        { k: "上线", v: "合并并部署" },
      ],
    },
    cta: {
      tag: "就绪",
      title: "唤醒 DJL",
      body: "打开工作区，让智能体在你的设备上用你的语言开始工作。",
      primary: "打开工作区",
      secondary: "阅读文档",
    },
    footer: {
      brand: "DJL",
      tag: "本地优先的智能体命令中心",
      status: "待命",
      cols: [
        { h: "产品", links: ["路由", "流程", "双语", "流水线"] },
        { h: "资源", links: ["文档", "更新日志", "隐私", "状态"] },
      ],
      note: "在你所在之处运行。",
    },
  },
} as const;

export type Content = (typeof content)[Locale];
