// Dev optimizer entry: export only the icons DJL uses, instead of whole icon packs.
// Keep named imports here when adding icons; production uses the original packages.
export {
  IconAdjustments,
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowBackUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowsUpDown,
  IconBell,
  IconBolt,
  IconBrain,
  IconBug,
  IconCamera,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCloud,
  IconColumns2,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFlag,
  IconFlame,
  IconFlask2,
  IconFolder,
  IconFolderOpen,
  IconHash,
  IconHistory,
  IconInfoCircle,
  IconKey,
  IconLayoutDistributeHorizontal,
  IconListCheck,
  IconListDetails,
  IconLoader2,
  IconLock,
  IconLockOpen,
  IconMaximize,
  IconMessageCircle,
  IconMinimize,
  IconMinus,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlugConnected,
  IconPlus,
  IconPrinter,
  IconRefresh,
  IconRocket,
  IconRotate2,
  IconSelector,
  IconSettings,
  IconShare3,
  IconSparkles,
  IconStack2,
  IconStar,
  IconStarFilled,
  IconSun,
  IconTerminal2,
  IconTextWrap,
  IconTrash,
  IconTrophy,
  IconUser,
  IconWifi,
  IconWorld,
  IconX,
} from "../node_modules/@tabler/icons-react/dist/esm/tabler-icons-react.mjs";
export { BsChat } from "../node_modules/react-icons/bs/index.mjs";
export { FaLinkedinIn, FaPlusMinus } from "../node_modules/react-icons/fa6/index.mjs";
export { FiArrowUp, FiGitBranch, FiPlus } from "../node_modules/react-icons/fi/index.mjs";
export { GoRepoForked, GoTasklist } from "../node_modules/react-icons/go/index.mjs";
export {
  HiMiniArrowsPointingOut,
  HiOutlineArchiveBox,
  HiOutlineCommandLine,
  HiOutlineFolderOpen,
  HiOutlineHandRaised,
  HiOutlinePencilSquare,
} from "../node_modules/react-icons/hi2/index.mjs";
export {
  IoIosArrowRoundBack,
  IoIosArrowRoundForward,
} from "../node_modules/react-icons/io/index.mjs";
export { IoFilter, IoStopSharp } from "../node_modules/react-icons/io5/index.mjs";
export {
  LuArrowDownToLine,
  LuArrowLeft,
  LuCornerLeftUp,
  LuFolderPlus,
} from "../node_modules/react-icons/lu/index.mjs";
export {
  PiArrowsInSimple,
  PiArrowsOutSimple,
  PiSidebarSimple,
  PiSlidersHorizontal,
  PiSquareSplitHorizontal,
  PiSquareSplitVertical,
} from "../node_modules/react-icons/pi/index.mjs";
export { RiApps2Line } from "../node_modules/react-icons/ri/index.mjs";
export {
  SiAndroidstudio,
  SiCanva,
  SiClion,
  SiDatagrip,
  SiFigma,
  SiGithub,
  SiGmail,
  SiGoland,
  SiGooglecalendar,
  SiGoogledrive,
  SiHuggingface,
  SiIntellijidea,
  SiLinear,
  SiNotion,
  SiOpenai,
  SiPhpstorm,
  SiPycharm,
  SiReddit,
  SiRider,
  SiRubymine,
  SiSlack,
  SiStripe,
  SiSublimetext,
  SiVercel,
  SiWarp,
  SiWebstorm,
  SiWindsurf,
  SiX,
  SiXcode,
} from "../node_modules/react-icons/si/index.mjs";
export {
  TbArrowsDiagonal,
  TbArrowsDiagonalMinimize2,
  TbCursorText,
  TbExchange,
} from "../node_modules/react-icons/tb/index.mjs";
export { VscMcp } from "../node_modules/react-icons/vsc/index.mjs";
